//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int AppId { get; set; }
        public int Department { get; set; }
        public int Title { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateClose { get; set; }
        public Nullable<bool> AppStatus { get; set; }
        public Nullable<int> Solved { get; set; }
    
        public virtual ApplicationDetail ApplicationDetail { get; set; }
        public virtual Department Department1 { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual ApplicationType ApplicationType { get; set; }
    }
}
