//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationDetail
    {
        public int Id { get; set; }
        public int Student { get; set; }
        public string Content { get; set; }
        public Nullable<int> FileAttached { get; set; }
        public string Solution { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual File File { get; set; }
        public virtual Student Student1 { get; set; }
    }
}
