//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassOfStudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClassOfStudent()
        {
            this.Grades = new HashSet<Grade>();
        }
    
        public int Id { get; set; }
        public int ClassId { get; set; }
        public int SemesterOfStudents { get; set; }
        public int SubjectId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual SemesterOfStudent SemesterOfStudent { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grade> Grades { get; set; }
    }
}
