//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curiculum
    {
        public int CuriculumId { get; set; }
        public int MajorId { get; set; }
        public int SubjectId { get; set; }
    
        public virtual Major Major { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
