//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int GradeId { get; set; }
        public int GradeItems { get; set; }
        public int ClassOfStudent { get; set; }
        public Nullable<decimal> Score { get; set; }
    
        public virtual ClassOfStudent ClassOfStudent1 { get; set; }
        public virtual GradeHasItem GradeHasItem { get; set; }
    }
}
