//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.ApplicationDetails = new HashSet<ApplicationDetail>();
            this.SemesterOfStudents = new HashSet<SemesterOfStudent>();
        }
    
        public int StudentId { get; set; }
        public string StudentCode { get; set; }
        public int UserId { get; set; }
        public int Major { get; set; }
        public System.DateTime EnrollmentDate { get; set; }
        public Nullable<int> Parent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationDetail> ApplicationDetails { get; set; }
        public virtual Major Major1 { get; set; }
        public virtual Parent Parent1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SemesterOfStudent> SemesterOfStudents { get; set; }
        public virtual User User { get; set; }
    }
}
