//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInformation
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string MidleName { get; set; }
        public string LastName { get; set; }
        public bool Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Avatar { get; set; }
        public Nullable<int> Contact { get; set; }
        public decimal Balance { get; set; }
    
        public virtual Contact Contact1 { get; set; }
        public virtual Image Image { get; set; }
        public virtual User User { get; set; }
    }
}
